services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest-app
    ports:
      - "${PORT}:${PORT}"   # Use env var
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  postgres-data:
