version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: jheer_sales
      POSTGRES_PASSWORD: jheer_sales
      POSTGRES_DB: jheer_sales_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

#docker exec -it postgres-container psql -U jheer_sales -d jheer_sales_db
